//
//  ElevenLabsPreviewAudioDBModel.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public struct ElevenLabsPreviewAudioDBModel: Codable, Sendable {
  public var audioUrl: String
  public var dashManifestUrl: String?
  public var generatedAtUnix: Int?
  public var hlsManifestUrl: String?
  public var isAutoGenerated: Bool?
  public var text: String?
  public var voiceId: String?

  public init(
    audioUrl: String,
    dashManifestUrl: String? = nil,
    generatedAtUnix: Int? = nil,
    hlsManifestUrl: String? = nil,
    isAutoGenerated: Bool? = nil,
    text: String? = nil,
    voiceId: String? = nil
  ) {
    self.audioUrl = audioUrl
    self.dashManifestUrl = dashManifestUrl
    self.generatedAtUnix = generatedAtUnix
    self.hlsManifestUrl = hlsManifestUrl
    self.isAutoGenerated = isAutoGenerated
    self.text = text
    self.voiceId = voiceId
  }

  enum CodingKeys: String, CodingKey {
    case audioUrl = "audio_url"
    case dashManifestUrl = "dash_manifest_url"
    case generatedAtUnix = "generated_at_unix"
    case hlsManifestUrl = "hls_manifest_url"
    case isAutoGenerated = "is_auto_generated"
    case text
    case voiceId = "voice_id"
  }
}
