//
//  TogetherDERolloutConditionCategory.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum TogetherDERolloutConditionCategory: String, Codable, Hashable, Sendable {
  case rOLLOUTFAILURECATEGORYMETRICREGRESSION = "ROLLOUT_FAILURE_CATEGORY_METRIC_REGRESSION"
  case rOLLOUTFAILURECATEGORYMETRICSUNAVAILABLE = "ROLLOUT_FAILURE_CATEGORY_METRICS_UNAVAILABLE"
  case rOLLOUTFAILURECATEGORYTARGETNOTREADY = "ROLLOUT_FAILURE_CATEGORY_TARGET_NOT_READY"
  case rOLLOUTFAILURECATEGORYSOURCENOTDRAINED = "ROLLOUT_FAILURE_CATEGORY_SOURCE_NOT_DRAINED"
  case rOLLOUTFAILURECATEGORYHEALTHREGRESSION = "ROLLOUT_FAILURE_CATEGORY_HEALTH_REGRESSION"
  case rOLLOUTFAILURECATEGORYCAPACITYEXHAUSTED = "ROLLOUT_FAILURE_CATEGORY_CAPACITY_EXHAUSTED"
  case rOLLOUTFAILURECATEGORYROUTINGERROR = "ROLLOUT_FAILURE_CATEGORY_ROUTING_ERROR"
  case rOLLOUTFAILURECATEGORYDEPENDENCYOUTAGE = "ROLLOUT_FAILURE_CATEGORY_DEPENDENCY_OUTAGE"
  case rOLLOUTFAILURECATEGORYABORTEDBYOPERATOR = "ROLLOUT_FAILURE_CATEGORY_ABORTED_BY_OPERATOR"
  case rOLLOUTFAILURECATEGORYINTERNAL = "ROLLOUT_FAILURE_CATEGORY_INTERNAL"
  case rOLLOUTFAILURECATEGORYPOLICYINFEASIBLE = "ROLLOUT_FAILURE_CATEGORY_POLICY_INFEASIBLE"
  case rOLLOUTFAILURECATEGORYUNDERSERVED = "ROLLOUT_FAILURE_CATEGORY_UNDER_SERVED"
  case rOLLOUTFAILURECATEGORYENTITLEMENTLAPSED = "ROLLOUT_FAILURE_CATEGORY_ENTITLEMENT_LAPSED"
}
