//
//  TogetherClusterPhaseTransitionPhase.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum TogetherClusterPhaseTransitionPhase: String, Codable, Hashable, Sendable {
  case cLUSTERPHASEQUEUED = "CLUSTER_PHASE_QUEUED"
  case cLUSTERPHASESCHEDULED = "CLUSTER_PHASE_SCHEDULED"
  case cLUSTERPHASEWAITINGFORCONTROLPLANENODES = "CLUSTER_PHASE_WAITING_FOR_CONTROL_PLANE_NODES"
  case cLUSTERPHASEWAITINGFORDATAPLANENODES = "CLUSTER_PHASE_WAITING_FOR_DATA_PLANE_NODES"
  case cLUSTERPHASEWAITINGFORSUBNET = "CLUSTER_PHASE_WAITING_FOR_SUBNET"
  case cLUSTERPHASEWAITINGFORSHAREDVOLUME = "CLUSTER_PHASE_WAITING_FOR_SHARED_VOLUME"
  case cLUSTERPHASEWAITINGFORAUTOSCALER = "CLUSTER_PHASE_WAITING_FOR_AUTO_SCALER"
  case cLUSTERPHASEINSTALLINGDRIVERS = "CLUSTER_PHASE_INSTALLING_DRIVERS"
  case cLUSTERPHASERUNNINGACCEPTANCETESTS = "CLUSTER_PHASE_RUNNING_ACCEPTANCE_TESTS"
  case cLUSTERPHASEACCEPTANCETESTSFAILED = "CLUSTER_PHASE_ACCEPTANCE_TESTS_FAILED"
  case cLUSTERPHASERUNNINGNCCLTESTS = "CLUSTER_PHASE_RUNNING_NCCL_TESTS"
  case cLUSTERPHASENCCLTESTSFAILED = "CLUSTER_PHASE_NCCL_TESTS_FAILED"
  case cLUSTERPHASEREADY = "CLUSTER_PHASE_READY"
  case cLUSTERPHASEPAUSED = "CLUSTER_PHASE_PAUSED"
  case cLUSTERPHASEONDEMANDCOMPUTEPAUSED = "CLUSTER_PHASE_ON_DEMAND_COMPUTE_PAUSED"
  case cLUSTERPHASEDEGRADED = "CLUSTER_PHASE_DEGRADED"
  case cLUSTERPHASEDELETING = "CLUSTER_PHASE_DELETING"
}
