//
//  DeepLConfiguredRulesDatesAndTimesTimeFormat.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum DeepLConfiguredRulesDatesAndTimesTimeFormat: String, Codable, Hashable, Sendable {
  case spellOutTimeInWords = "spell_out_time_in_words"
  case use12HourClockAndDoNotSpecifyMorningOrEvening =
    "use_12_hour_clock_and_do_not_specify_morning_or_evening"
  case use12HourClockAndLowercaseAmOrPmWithPeriods =
    "use_12_hour_clock_and_lowercase_am_or_pm_with_periods"
  case use12HourClockAndLowercaseAmOrPmWithPeriodsExceptUseNoonAndMidnightInsteadOf12AmAnd12Pm =
    "use_12_hour_clock_and_lowercase_am_or_pm_with_periods_except_use_noon_and_midnight_instead_of_12_am_and_12_pm"
  case use12HourClockAndLowercaseAmOrPmWithoutPeriods =
    "use_12_hour_clock_and_lowercase_am_or_pm_without_periods"
  case use12HourClockAndLowercaseAmOrPmWithoutPeriodsExceptUseNoonAndMidnightInsteadOf12AmAnd12Pm =
    "use_12_hour_clock_and_lowercase_am_or_pm_without_periods_except_use_noon_and_midnight_instead_of_12_am_and_12_pm"
  case use12HourClockAndSpecifyMorningOrEvening = "use_12_hour_clock_and_specify_morning_or_evening"
  case use12HourClockAndUppercaseAmOrPmWithPeriods =
    "use_12_hour_clock_and_uppercase_am_or_pm_with_periods"
  case use12HourClockAndUppercaseAmOrPmWithPeriodsExceptUseNoonAndMidnightInsteadOf12AmAnd12Pm =
    "use_12_hour_clock_and_uppercase_am_or_pm_with_periods_except_use_noon_and_midnight_instead_of_12_am_and_12_pm"
  case use12HourClockAndUppercaseAmOrPmWithoutPeriods =
    "use_12_hour_clock_and_uppercase_am_or_pm_without_periods"
  case use12HourClockAndUppercaseAmOrPmWithoutPeriodsExceptUseNoonAndMidnightInsteadOf12AmAnd12Pm =
    "use_12_hour_clock_and_uppercase_am_or_pm_without_periods_except_use_noon_and_midnight_instead_of_12_am_and_12_pm"
  case use12HourClockAndWriteChineseWordOrOrChineseWordOrFollowedByArabicNumerals =
    "use_12_hour_clock_and_write_chinese_word_上午_or_下午_or_chinese_word_早上_or_晚上_followed_by_arabic_numerals"
  case
    use12HourClockAndWriteChineseWordOrOrChineseWordOrFollowedByArabicNumeralsWithChineseWordForHours =
    "use_12_hour_clock_and_write_chinese_word_上午_or_下午_or_chinese_word_早上_or_晚上_followed_by_arabic_numerals_with_chinese_word_点_for_hours"
  case
    use12HourClockAndWriteChineseWordOrOrChineseWordOrFollowedByArabicNumeralsWithChineseWordsAndForHoursAndMinutes =
    "use_12_hour_clock_and_write_chinese_word_上午_or_下午_or_chinese_word_早上_or_晚上_followed_by_arabic_numerals_with_chinese_words_时_and_分_for_hours_and_minutes"
  case
    use12HourClockAndWriteChineseWordOrOrChineseWordOrFollowedByChineseNumbersWithChineseWordsAndForHoursAndMinutes =
    "use_12_hour_clock_and_write_chinese_word_上午_or_下午_or_chinese_word_早上_or_晚上_followed_by_chinese_numbers_with_chinese_words_时_and_分_for_hours_and_minutes"
  case use12HourClockWithArabicNumeralsAndColon = "use_12_hour_clock_with_arabic_numerals_and_colon"
  case use12HourClockWithKoreanWordsAnd = "use_12_hour_clock_with_korean_words_시_and_분"
  case
    use12HourClockWithoutLeadingZeroOrMinutesForFullHoursUseColonAsSeparatorAndLowercaseAmOrPmWithoutPeriods =
    "use_12_hour_clock_without_leading_zero_or_minutes_for_full_hours_use_colon_as_separator_and_lowercase_am_or_pm_without_periods"
  case
    use12HourClockWithoutLeadingZeroOrMinutesForFullHoursUseColonAsSeparatorAndUppercaseAmOrPmWithoutPeriods =
    "use_12_hour_clock_without_leading_zero_or_minutes_for_full_hours_use_colon_as_separator_and_uppercase_am_or_pm_without_periods"
  case use12HourClockWithoutLeadingZeroUsePeriodAsSeparatorAndLowercaseAmOrPmWithPeriodsAndSpaces =
    "use_12_hour_clock_without_leading_zero_use_period_as_separator_and_lowercase_am_or_pm_with_periods_and_spaces"
  case use24HourClock = "use_24_hour_clock"
  case use24HourClockWithArabicNumeralsAndColon = "use_24_hour_clock_with_arabic_numerals_and_colon"
  case use24HourClockWithColonAsSeparator = "use_24_hour_clock_with_colon_as_separator"
  case use24HourClockWithKoreanWordsAnd = "use_24_hour_clock_with_korean_words_시_and_분"
  case use24HourClockWithPeriodAsSeparator = "use_24_hour_clock_with_period_as_separator"
  case useHhColonMmGermanWordUhrWithLeadingZerosForSingleDigitHours =
    "use_hh_colon_mm_german_word_uhr_with_leading_zeros_for_single_digit_hours"
  case useHhColonMmGermanWordUhrWithoutLeadingZerosForSingleDigitHours =
    "use_hh_colon_mm_german_word_uhr_without_leading_zeros_for_single_digit_hours"
  case useHhPeriodMmGermanWordUhrWithLeadingZerosForSingleDigitHours =
    "use_hh_period_mm_german_word_uhr_with_leading_zeros_for_single_digit_hours"
  case useHhPeriodMmGermanWordUhrWithoutLeadingZerosForSingleDigitHours =
    "use_hh_period_mm_german_word_uhr_without_leading_zeros_for_single_digit_hours"
  case
    useHhPeriodMmGermanWordUhrWithoutLeadingZerosForSingleDigitHoursAndForFullHoursStateHourOnly =
    "use_hh_period_mm_german_word_uhr_without_leading_zeros_for_single_digit_hours_and_for_full_hours_state_hour_only"
}
