//
//  DeepLConfiguredRulesPunctuationQuotationStyle.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum DeepLConfiguredRulesPunctuationQuotationStyle: String, Codable, Hashable, Sendable {
  case useCornerBracketsForPrimaryQuotationsAndDoubleCornerBracketsForSecondaryQuotations =
    "use_corner_brackets_for_primary_quotations_and_double_corner_brackets_for_secondary_quotations"
  case
    useDoubleCurlyQuotationMarksForPrimaryQuotationsAndSingleCurlyQuotationMarksForSecondaryQuotations =
    "use_double_curly_quotation_marks_for_primary_quotations_and_single_curly_quotation_marks_for_secondary_quotations"
  case
    useDoubleCurlyQuotationMarksForPrimaryQuotationsThenAlternateWithSingleCurlyQuotationMarksForNestedQuotations =
    "use_double_curly_quotation_marks_for_primary_quotations_then_alternate_with_single_curly_quotation_marks_for_nested_quotations"
  case
    useDoubleGermanQuotationMarksForPrimaryQuotationsAndSingleGermanQuotationMarksForSecondaryQuotations =
    "use_double_german_quotation_marks_for_primary_quotations_and_single_german_quotation_marks_for_secondary_quotations"
  case useDoubleQuotationMarksForPrimaryQuotationsAndSingleQuotationMarksForSecondaryQuotations =
    "use_double_quotation_marks_for_primary_quotations_and_single_quotation_marks_for_secondary_quotations"
  case
    useDoubleStraightQuotationMarksForPrimaryQuotationsAndSingleStraightQuotationMarksForSecondaryQuotations =
    "use_double_straight_quotation_marks_for_primary_quotations_and_single_straight_quotation_marks_for_secondary_quotations"
  case
    useDoubleStraightQuotationMarksForPrimaryQuotationsThenAlternateWithSingleStraightQuotationMarksForNestedQuotations =
    "use_double_straight_quotation_marks_for_primary_quotations_then_alternate_with_single_straight_quotation_marks_for_nested_quotations"
  case useGuillemetsForPrimaryQuotationsAndDoubleCurlyQuotationMarksForSecondaryQuotations =
    "use_guillemets_for_primary_quotations_and_double_curly_quotation_marks_for_secondary_quotations"
  case useGuillemetsForPrimaryQuotationsAndDoubleStraightQuotationMarksForSecondaryQuotations =
    "use_guillemets_for_primary_quotations_and_double_straight_quotation_marks_for_secondary_quotations"
  case useGuillemetsForPrimaryQuotationsAndSingleGuillemetsForSecondaryQuotations =
    "use_guillemets_for_primary_quotations_and_single_guillemets_for_secondary_quotations"
  case
    useGuillemetsForPrimaryQuotationsDoubleCurlyQuotationMarksForSecondaryQuotationsAndSingleCurlyQuotationMarksForFurtherNestedQuotations =
    "use_guillemets_for_primary_quotations_double_curly_quotation_marks_for_secondary_quotations_and_single_curly_quotation_marks_for_further_nested_quotations"
  case useReversedGuillemetsForPrimaryQuotationsAndSingleReversedGuillemetsForSecondaryQuotations =
    "use_reversed_guillemets_for_primary_quotations_and_single_reversed_guillemets_for_secondary_quotations"
  case useSingleQuotationMarksForPrimaryQuotationsAndDoubleQuotationMarksForSecondaryQuotations =
    "use_single_quotation_marks_for_primary_quotations_and_double_quotation_marks_for_secondary_quotations"
}
