//
//  DeepLConfiguredRulesDatesAndTimesDateFormat.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum DeepLConfiguredRulesDatesAndTimesDateFormat: String, Codable, Hashable, Sendable {
  case useDdPeriodMmPeriodYyWithLeadingZerosForSingleDigitDaysAndMonths =
    "use_dd_period_mm_period_yy_with_leading_zeros_for_single_digit_days_and_months"
  case useDdPeriodMmPeriodYyyy = "use_dd_period_mm_period_yyyy"
  case useDdPeriodMmPeriodYyyyWithLeadingZerosForSingleDigitDaysAndMonths =
    "use_dd_period_mm_period_yyyy_with_leading_zeros_for_single_digit_days_and_months"
  case
    useDdPeriodSpaceAbbreviatedMonthYyyyWithAbbreviationsJanPeriodFebPeriodMrzPeriodAprPeriodMaiJunPeriodJulPeriodAugPeriodSepPeriodOktPeriodNovPeriodDezPeriodWithoutLeadingZerosForSingleDigitDays =
    "use_dd_period_space_abbreviated_month_yyyy_with_abbreviations_jan_period_feb_period_mrz_period_apr_period_mai_jun_period_jul_period_aug_period_sep_period_okt_period_nov_period_dez_period_without_leading_zeros_for_single_digit_days"
  case
    useDdPeriodSpaceAbbreviatedMonthYyyyWithAbbreviationsJanPeriodFebrPeriodMaerzAprPeriodMaiJuniJuliAugPeriodSeptPeriodOktPeriodNovPeriodDezPeriodWithoutLeadingZerosForSingleDigitDays =
    "use_dd_period_space_abbreviated_month_yyyy_with_abbreviations_jan_period_febr_period_maerz_apr_period_mai_juni_juli_aug_period_sept_period_okt_period_nov_period_dez_period_without_leading_zeros_for_single_digit_days"
  case useDdPeriodSpaceMonthYyyyWithoutLeadingZerosForSingleDigitDays =
    "use_dd_period_space_month_yyyy_without_leading_zeros_for_single_digit_days"
  case useDdSlashMmSlashYyyy = "use_dd_slash_mm_slash_yyyy"
  case useDdSlashMmSlashYyyyWithLeadingZerosForSingleDigitDaysAndMonths =
    "use_dd_slash_mm_slash_yyyy_with_leading_zeros_for_single_digit_days_and_months"
  case useDdSpaceSpelledOutMonthSpaceYyyy = "use_dd_space_spelled_out_month_space_yyyy"
  case useDdSpaceSpelledOutMonthSpaceYyyyAndUseSpanishWordSeptiembreForNinthMonth =
    "use_dd_space_spelled_out_month_space_yyyy_and_use_spanish_word_septiembre_for_ninth_month"
  case useDdSpaceSpelledOutMonthSpaceYyyyAndUseSpanishWordSetiembreForNinthMonth =
    "use_dd_space_spelled_out_month_space_yyyy_and_use_spanish_word_setiembre_for_ninth_month"
  case useDdSpaceSpelledOutMonthSpaceYyyyWithoutLeadingZerosForSingleDigitDays =
    "use_dd_space_spelled_out_month_space_yyyy_without_leading_zeros_for_single_digit_days"
  case
    useHistoricalErasAndWriteNumbersInChineseFollowedByChineseWordOrWithArabicNumeralsInParentheses =
    "use_historical_eras_and_write_numbers_in_chinese_followed_by_chinese_word_公元前_or_公元后_with_arabic_numerals_in_parentheses"
  case useMmSlashDdSlashYyyyWithLeadingZerosForSingleDigitDaysAndMonths =
    "use_mm_slash_dd_slash_yyyy_with_leading_zeros_for_single_digit_days_and_months"
  case useNumeralsOnlyWithLeadingZeroForSingleDigits =
    "use_numerals_only_with_leading_zero_for_single_digits"
  case useNumeralsOnlyWithoutLeadingZeroForSingleDigits =
    "use_numerals_only_without_leading_zero_for_single_digits"
  case useSpelledOutMonthSpaceDdCommaSpaceYyyyAndUseSpanishWordSeptiembreForNinthMonth =
    "use_spelled_out_month_space_dd_comma_space_yyyy_and_use_spanish_word_septiembre_for_ninth_month"
  case useSpelledOutMonthSpaceDdCommaSpaceYyyyWithoutLeadingZerosForSingleDigitDays =
    "use_spelled_out_month_space_dd_comma_space_yyyy_without_leading_zeros_for_single_digit_days"
  case useTraditionalCalendarSystemWithChineseNumbers =
    "use_traditional_calendar_system_with_chinese_numbers"
  case useYyyyChineseWordMmChineseWordDdChineseWordWithChineseNumbers =
    "use_yyyy_chinese_word_年_mm_chinese_word_月_dd_chinese_word_日_with_chinese_numbers"
  case useYyyyChineseWordMmChineseWordDdChineseWordWithoutLeadingZeroForSingleDigitMonthsAndDays =
    "use_yyyy_chinese_word_年_mm_chinese_word_月_dd_chinese_word_日_without_leading_zero_for_single_digit_months_and_days"
  case useYyyyHyphenMmHyphenDdWithLeadingZeroForSingleDigitDaysAndMonths =
    "use_yyyy_hyphen_mm_hyphen_dd_with_leading_zero_for_single_digit_days_and_months"
  case useYyyyHyphenMmHyphenDdWithLeadingZerosForSingleDigitDaysAndMonths =
    "use_yyyy_hyphen_mm_hyphen_dd_with_leading_zeros_for_single_digit_days_and_months"
  case
    useYyyyKoreanWordSpaceMmKoreanWordSpaceDdKoreanWordWithoutLeadingZeroForSingleDigitDaysAndMonths =
    "use_yyyy_korean word_년_space_mm_korean word_월_space_dd_korean word_일_without_leading_zero_for_single_digit_days_and_months"
  case useYyyyPeriodMmPeriodDd = "use_yyyy_period_mm_period_dd"
  case useYyyyPeriodSpaceMmPeriodSpaceDdPeriodSpaceWithoutLeadingZeroForSingleDigitDaysAndMonths =
    "use_yyyy_period_space_mm_period_space_dd_period_space_without_leading_zero_for_single_digit_days_and_months"
  case useYyyySlashMmSlashDd = "use_yyyy_slash_mm_slash_dd"
  case useYyyySlashMmSlashDdWithLeadingZeroForSingleDigitDaysAndMonths =
    "use_yyyy_slash_mm_slash_dd_with_leading_zero_for_single_digit_days_and_months"
}
