//
//  GeminiSafetySettingCategory.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum GeminiSafetySettingCategory: String, Codable, Hashable, Sendable {
  case hARMCATEGORYUNSPECIFIED = "HARM_CATEGORY_UNSPECIFIED"
  case hARMCATEGORYDEROGATORY = "HARM_CATEGORY_DEROGATORY"
  case hARMCATEGORYTOXICITY = "HARM_CATEGORY_TOXICITY"
  case hARMCATEGORYVIOLENCE = "HARM_CATEGORY_VIOLENCE"
  case hARMCATEGORYSEXUAL = "HARM_CATEGORY_SEXUAL"
  case hARMCATEGORYMEDICAL = "HARM_CATEGORY_MEDICAL"
  case hARMCATEGORYDANGEROUS = "HARM_CATEGORY_DANGEROUS"
  case hARMCATEGORYHARASSMENT = "HARM_CATEGORY_HARASSMENT"
  case hARMCATEGORYHATESPEECH = "HARM_CATEGORY_HATE_SPEECH"
  case hARMCATEGORYSEXUALLYEXPLICIT = "HARM_CATEGORY_SEXUALLY_EXPLICIT"
  case hARMCATEGORYDANGEROUSCONTENT = "HARM_CATEGORY_DANGEROUS_CONTENT"
  case hARMCATEGORYCIVICINTEGRITY = "HARM_CATEGORY_CIVIC_INTEGRITY"
  case hARMCATEGORYJAILBREAK = "HARM_CATEGORY_JAILBREAK"
}
