//
//  GeminiImageResponseFormatAspectRatio.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum GeminiImageResponseFormatAspectRatio: String, Codable, Hashable, Sendable {
  case aSPECTRATIOUNSPECIFIED = "ASPECT_RATIO_UNSPECIFIED"
  case aSPECTRATIOONEBYONE = "ASPECT_RATIO_ONE_BY_ONE"
  case aSPECTRATIOTWOBYTHREE = "ASPECT_RATIO_TWO_BY_THREE"
  case aSPECTRATIOTHREEBYTWO = "ASPECT_RATIO_THREE_BY_TWO"
  case aSPECTRATIOTHREEBYFOUR = "ASPECT_RATIO_THREE_BY_FOUR"
  case aSPECTRATIOFOURBYTHREE = "ASPECT_RATIO_FOUR_BY_THREE"
  case aSPECTRATIOFOURBYFIVE = "ASPECT_RATIO_FOUR_BY_FIVE"
  case aSPECTRATIOFIVEBYFOUR = "ASPECT_RATIO_FIVE_BY_FOUR"
  case aSPECTRATIONINEBYSIXTEEN = "ASPECT_RATIO_NINE_BY_SIXTEEN"
  case aSPECTRATIOSIXTEENBYNINE = "ASPECT_RATIO_SIXTEEN_BY_NINE"
  case aSPECTRATIOTWENTYONEBYNINE = "ASPECT_RATIO_TWENTY_ONE_BY_NINE"
  case aSPECTRATIOONEBYEIGHT = "ASPECT_RATIO_ONE_BY_EIGHT"
  case aSPECTRATIOEIGHTBYONE = "ASPECT_RATIO_EIGHT_BY_ONE"
  case aSPECTRATIOONEBYFOUR = "ASPECT_RATIO_ONE_BY_FOUR"
  case aSPECTRATIOFOURBYONE = "ASPECT_RATIO_FOUR_BY_ONE"
}
