//
//  OpenRouterProviderName.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum OpenRouterProviderName: String, Codable, Hashable, Sendable {
  case modal = "Modal"
  case akashML = "AkashML"
  case aI21 = "AI21"
  case aionLabs = "AionLabs"
  case alibaba = "Alibaba"
  case ambient = "Ambient"
  case baidu = "Baidu"
  case amazonBedrock = "Amazon Bedrock"
  case amazonNova = "Amazon Nova"
  case anthropic = "Anthropic"
  case arceeAI = "Arcee AI"
  case assemblyAI = "AssemblyAI"
  case atlasCloud = "AtlasCloud"
  case avian = "Avian"
  case azure = "Azure"
  case baseTen = "BaseTen"
  case bytePlus = "BytePlus"
  case blackForestLabs = "Black Forest Labs"
  case cerebras = "Cerebras"
  case chutes = "Chutes"
  case cirrascale = "Cirrascale"
  case claudePlatformOnAWS = "Claude Platform on AWS"
  case clarifai = "Clarifai"
  case cloudflare = "Cloudflare"
  case cohere = "Cohere"
  case coreWeave = "CoreWeave"
  case cosine = "Cosine"
  case crucible = "Crucible"
  case crusoe = "Crusoe"
  case darkbloom = "Darkbloom"
  case databricks = "Databricks"
  case decart = "Decart"
  case deepgram = "Deepgram"
  case deepInfra = "DeepInfra"
  case deepSeek = "DeepSeek"
  case dekaLLM = "DekaLLM"
  case digitalOcean = "DigitalOcean"
  case featherless = "Featherless"
  case fireworks = "Fireworks"
  case fishAudio = "Fish Audio"
  case friendli = "Friendli"
  case gMICloud = "GMICloud"
  case google = "Google"
  case googleAIStudio = "Google AI Studio"
  case groq = "Groq"
  case heyGen = "HeyGen"
  case inception = "Inception"
  case inceptron = "Inceptron"
  case inferenceNet = "InferenceNet"
  case ionstream = "Ionstream"
  case infermatic = "Infermatic"
  case ioNet = "Io Net"
  case inferactVLLM = "Inferact vLLM"
  case inflection = "Inflection"
  case liquid = "Liquid"
  case makora = "Makora"
  case mara = "Mara"
  case mancer2 = "Mancer 2"
  case meta = "Meta"
  case minimax = "Minimax"
  case modelRun = "ModelRun"
  case mistral = "Mistral"
  case modular = "Modular"
  case moonshotAI = "Moonshot AI"
  case morph = "Morph"
  case voyageAIByMongoDB = "VoyageAI by MongoDB"
  case typeSafe = "TypeSafe"
  case nearAI = "Near AI"
  case nebius = "Nebius"
  case nexAGI = "Nex AGI"
  case nextBit = "NextBit"
  case novita = "Novita"
  case nvidia = "Nvidia"
  case ollama = "Ollama"
  case openAI = "OpenAI"
  case openInference = "OpenInference"
  case parasail = "Parasail"
  case poolside = "Poolside"
  case primeIntellect = "PrimeIntellect"
  case perceptron = "Perceptron"
  case perplexity = "Perplexity"
  case phala = "Phala"
  case recraft = "Recraft"
  case reka = "Reka"
  case relace = "Relace"
  case sailResearch = "Sail Research"
  case sakanaAI = "Sakana AI"
  case sambaNova = "SambaNova"
  case seed = "Seed"
  case siliconFlow = "SiliconFlow"
  case sourceful = "Sourceful"
  case stepFun = "StepFun"
  case stealth = "Stealth"
  case streamLake = "StreamLake"
  case switchpoint = "Switchpoint"
  case tencent = "Tencent"
  case tenstorrent = "Tenstorrent"
  case thinkingMachines = "Thinking Machines"
  case together = "Together"
  case unbiased = "Unbiased"
  case upstage = "Upstage"
  case venice = "Venice"
  case wafer = "Wafer"
  case wandB = "WandB"
  case quiver = "Quiver"
  case krea = "Krea"
  case runway = "Runway"
  case xiaomi = "Xiaomi"
  case xAI = "xAI"
  case zAI = "Z.AI"
  case fakeProvider = "FakeProvider"
}
