//
//  OpenRouterBYOKProviderSlug.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public struct OpenRouterBYOKProviderSlug: RawRepresentable, Codable, Hashable, Sendable {
  public var rawValue: String

  public init(rawValue: String) {
    self.rawValue = rawValue
  }

  public static let ai21 = Self(rawValue: "ai21")
  public static let aionLabs = Self(rawValue: "aion-labs")
  public static let akashml = Self(rawValue: "akashml")
  public static let alibaba = Self(rawValue: "alibaba")
  public static let amazonBedrock = Self(rawValue: "amazon-bedrock")
  public static let amazonBedrockClaudeOnAws = Self(rawValue: "amazon-bedrock/claude-on-aws")
  public static let amazonNova = Self(rawValue: "amazon-nova")
  public static let ambient = Self(rawValue: "ambient")
  public static let anthropic = Self(rawValue: "anthropic")
  public static let anthropic2 = Self(rawValue: "anthropic/2")
  public static let arceeAi = Self(rawValue: "arcee-ai")
  public static let atlasCloud = Self(rawValue: "atlas-cloud")
  public static let avian = Self(rawValue: "avian")
  public static let azure = Self(rawValue: "azure")
  public static let baidu = Self(rawValue: "baidu")
  public static let baseten = Self(rawValue: "baseten")
  public static let blackForestLabs = Self(rawValue: "black-forest-labs")
  public static let byteplus = Self(rawValue: "byteplus")
  public static let cerebras = Self(rawValue: "cerebras")
  public static let chutes = Self(rawValue: "chutes")
  public static let cirrascale = Self(rawValue: "cirrascale")
  public static let clarifai = Self(rawValue: "clarifai")
  public static let claudeOnAws = Self(rawValue: "claude-on-aws")
  public static let cloudflare = Self(rawValue: "cloudflare")
  public static let cohere = Self(rawValue: "cohere")
  public static let coreweave = Self(rawValue: "coreweave")
  public static let cosine = Self(rawValue: "cosine")
  public static let crusoe = Self(rawValue: "crusoe")
  public static let darkbloom = Self(rawValue: "darkbloom")
  public static let databricks = Self(rawValue: "databricks")
  public static let decart = Self(rawValue: "decart")
  public static let deepgram = Self(rawValue: "deepgram")
  public static let deepinfra = Self(rawValue: "deepinfra")
  public static let deepseek = Self(rawValue: "deepseek")
  public static let dekallm = Self(rawValue: "dekallm")
  public static let digitalocean = Self(rawValue: "digitalocean")
  public static let featherless = Self(rawValue: "featherless")
  public static let fireworks = Self(rawValue: "fireworks")
  public static let fishAudio = Self(rawValue: "fish-audio")
  public static let friendli = Self(rawValue: "friendli")
  public static let gmicloud = Self(rawValue: "gmicloud")
  public static let googleAiStudio = Self(rawValue: "google-ai-studio")
  public static let googleVertex = Self(rawValue: "google-vertex")
  public static let groq = Self(rawValue: "groq")
  public static let heygen = Self(rawValue: "heygen")
  public static let inception = Self(rawValue: "inception")
  public static let inceptron = Self(rawValue: "inceptron")
  public static let inferactVllm = Self(rawValue: "inferact-vllm")
  public static let inferenceNet = Self(rawValue: "inference-net")
  public static let infermatic = Self(rawValue: "infermatic")
  public static let inflection = Self(rawValue: "inflection")
  public static let ioNet = Self(rawValue: "io-net")
  public static let ionstream = Self(rawValue: "ionstream")
  public static let krea = Self(rawValue: "krea")
  public static let liquid = Self(rawValue: "liquid")
  public static let makora = Self(rawValue: "makora")
  public static let mancer = Self(rawValue: "mancer")
  public static let mara = Self(rawValue: "mara")
  public static let meta = Self(rawValue: "meta")
  public static let minimax = Self(rawValue: "minimax")
  public static let mistral = Self(rawValue: "mistral")
  public static let modal = Self(rawValue: "modal")
  public static let modelrun = Self(rawValue: "modelrun")
  public static let modular = Self(rawValue: "modular")
  public static let moonshotai = Self(rawValue: "moonshotai")
  public static let morph = Self(rawValue: "morph")
  public static let nearAi = Self(rawValue: "near-ai")
  public static let nebius = Self(rawValue: "nebius")
  public static let nexAgi = Self(rawValue: "nex-agi")
  public static let nextbit = Self(rawValue: "nextbit")
  public static let novita = Self(rawValue: "novita")
  public static let nvidia = Self(rawValue: "nvidia")
  public static let ollama = Self(rawValue: "ollama")
  public static let openInference = Self(rawValue: "open-inference")
  public static let openai = Self(rawValue: "openai")
  public static let parasail = Self(rawValue: "parasail")
  public static let perceptron = Self(rawValue: "perceptron")
  public static let perplexity = Self(rawValue: "perplexity")
  public static let phala = Self(rawValue: "phala")
  public static let poolside = Self(rawValue: "poolside")
  public static let primeintellect = Self(rawValue: "primeintellect")
  public static let quiver = Self(rawValue: "quiver")
  public static let recraft = Self(rawValue: "recraft")
  public static let reka = Self(rawValue: "reka")
  public static let relace = Self(rawValue: "relace")
  public static let runway = Self(rawValue: "runway")
  public static let sailResearch = Self(rawValue: "sail-research")
  public static let sakana = Self(rawValue: "sakana")
  public static let sakanaAi = Self(rawValue: "sakana-ai")
  public static let sambanova = Self(rawValue: "sambanova")
  public static let seed = Self(rawValue: "seed")
  public static let siliconflow = Self(rawValue: "siliconflow")
  public static let sourceful = Self(rawValue: "sourceful")
  public static let stepfun = Self(rawValue: "stepfun")
  public static let streamlake = Self(rawValue: "streamlake")
  public static let switchpoint = Self(rawValue: "switchpoint")
  public static let tencent = Self(rawValue: "tencent")
  public static let tenstorrent = Self(rawValue: "tenstorrent")
  public static let thinkingmachines = Self(rawValue: "thinkingmachines")
  public static let together = Self(rawValue: "together")
  public static let upstage = Self(rawValue: "upstage")
  public static let venice = Self(rawValue: "venice")
  public static let voyageai = Self(rawValue: "voyageai")
  public static let wafer = Self(rawValue: "wafer")
  public static let wandb = Self(rawValue: "wandb")
  public static let wandbLegacy = Self(rawValue: "wandb-legacy")
  public static let xai = Self(rawValue: "xai")
  public static let xiaomi = Self(rawValue: "xiaomi")
  public static let zAi = Self(rawValue: "z-ai")
}
