//
//  OpenRouterListBYOKKeysParametersProvider.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum OpenRouterListBYOKKeysParametersProvider: String, Codable, Hashable, Sendable {
  case ai21 = "ai21"
  case aionLabs = "aion-labs"
  case akashml = "akashml"
  case alibaba = "alibaba"
  case amazonBedrock = "amazon-bedrock"
  case amazonBedrockClaudeOnAws = "amazon-bedrock/claude-on-aws"
  case amazonNova = "amazon-nova"
  case ambient = "ambient"
  case anthropic = "anthropic"
  case anthropic2 = "anthropic/2"
  case arceeAi = "arcee-ai"
  case assemblyai = "assemblyai"
  case atlasCloud = "atlas-cloud"
  case avian = "avian"
  case azure = "azure"
  case baidu = "baidu"
  case baseten = "baseten"
  case blackForestLabs = "black-forest-labs"
  case byteplus = "byteplus"
  case cerebras = "cerebras"
  case chutes = "chutes"
  case cirrascale = "cirrascale"
  case clarifai = "clarifai"
  case claudeOnAws = "claude-on-aws"
  case cloudflare = "cloudflare"
  case cohere = "cohere"
  case coreweave = "coreweave"
  case cosine = "cosine"
  case crusoe = "crusoe"
  case darkbloom = "darkbloom"
  case databricks = "databricks"
  case decart = "decart"
  case deepgram = "deepgram"
  case deepinfra = "deepinfra"
  case deepseek = "deepseek"
  case dekallm = "dekallm"
  case digitalocean = "digitalocean"
  case featherless = "featherless"
  case fireworks = "fireworks"
  case fishAudio = "fish-audio"
  case friendli = "friendli"
  case gmicloud = "gmicloud"
  case googleAiStudio = "google-ai-studio"
  case googleVertex = "google-vertex"
  case groq = "groq"
  case heygen = "heygen"
  case inception = "inception"
  case inceptron = "inceptron"
  case inferactVllm = "inferact-vllm"
  case inferenceNet = "inference-net"
  case infermatic = "infermatic"
  case inflection = "inflection"
  case ioNet = "io-net"
  case ionstream = "ionstream"
  case krea = "krea"
  case liquid = "liquid"
  case makora = "makora"
  case mancer = "mancer"
  case mara = "mara"
  case meta = "meta"
  case minimax = "minimax"
  case mistral = "mistral"
  case modal = "modal"
  case modelrun = "modelrun"
  case modular = "modular"
  case moonshotai = "moonshotai"
  case morph = "morph"
  case nearAi = "near-ai"
  case nebius = "nebius"
  case nexAgi = "nex-agi"
  case nextbit = "nextbit"
  case novita = "novita"
  case nvidia = "nvidia"
  case ollama = "ollama"
  case openInference = "open-inference"
  case openai = "openai"
  case parasail = "parasail"
  case perceptron = "perceptron"
  case perplexity = "perplexity"
  case phala = "phala"
  case poolside = "poolside"
  case primeintellect = "primeintellect"
  case quiver = "quiver"
  case recraft = "recraft"
  case reka = "reka"
  case relace = "relace"
  case runway = "runway"
  case sailResearch = "sail-research"
  case sakana = "sakana"
  case sakanaAi = "sakana-ai"
  case sambanova = "sambanova"
  case seed = "seed"
  case siliconflow = "siliconflow"
  case sourceful = "sourceful"
  case stepfun = "stepfun"
  case streamlake = "streamlake"
  case switchpoint = "switchpoint"
  case tencent = "tencent"
  case tenstorrent = "tenstorrent"
  case thinkingmachines = "thinkingmachines"
  case together = "together"
  case typesafe = "typesafe"
  case unbiased = "unbiased"
  case upstage = "upstage"
  case venice = "venice"
  case voyageai = "voyageai"
  case wafer = "wafer"
  case wandb = "wandb"
  case wandbLegacy = "wandb-legacy"
  case xai = "xai"
  case xiaomi = "xiaomi"
  case zAi = "z-ai"
}
