//
//  OpenAIAuditLogEventType.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum OpenAIAuditLogEventType: String, Codable, Hashable, Sendable {
  case apiKeyCreated = "api_key.created"
  case apiKeyUpdated = "api_key.updated"
  case apiKeyDeleted = "api_key.deleted"
  case certificateCreated = "certificate.created"
  case certificateUpdated = "certificate.updated"
  case certificateDeleted = "certificate.deleted"
  case certificatesActivated = "certificates.activated"
  case certificatesDeactivated = "certificates.deactivated"
  case checkpointPermissionCreated = "checkpoint.permission.created"
  case checkpointPermissionDeleted = "checkpoint.permission.deleted"
  case externalKeyRegistered = "external_key.registered"
  case externalKeyRemoved = "external_key.removed"
  case externalStorageRegistered = "external_storage.registered"
  case externalStorageRemoved = "external_storage.removed"
  case groupCreated = "group.created"
  case groupUpdated = "group.updated"
  case groupDeleted = "group.deleted"
  case inviteSent = "invite.sent"
  case inviteAccepted = "invite.accepted"
  case inviteDeleted = "invite.deleted"
  case ipAllowlistCreated = "ip_allowlist.created"
  case ipAllowlistUpdated = "ip_allowlist.updated"
  case ipAllowlistDeleted = "ip_allowlist.deleted"
  case ipAllowlistConfigActivated = "ip_allowlist.config.activated"
  case ipAllowlistConfigDeactivated = "ip_allowlist.config.deactivated"
  case loginSucceeded = "login.succeeded"
  case loginFailed = "login.failed"
  case logoutSucceeded = "logout.succeeded"
  case logoutFailed = "logout.failed"
  case organizationUpdated = "organization.updated"
  case projectCreated = "project.created"
  case projectUpdated = "project.updated"
  case projectArchived = "project.archived"
  case projectDeleted = "project.deleted"
  case rateLimitUpdated = "rate_limit.updated"
  case rateLimitDeleted = "rate_limit.deleted"
  case resourceDeleted = "resource.deleted"
  case tunnelCreated = "tunnel.created"
  case tunnelUpdated = "tunnel.updated"
  case tunnelDeleted = "tunnel.deleted"
  case workloadIdentityProviderCreated = "workload_identity_provider.created"
  case workloadIdentityProviderUpdated = "workload_identity_provider.updated"
  case workloadIdentityProviderDeleted = "workload_identity_provider.deleted"
  case workloadIdentityProviderMappingCreated = "workload_identity_provider_mapping.created"
  case workloadIdentityProviderMappingUpdated = "workload_identity_provider_mapping.updated"
  case workloadIdentityProviderMappingDeleted = "workload_identity_provider_mapping.deleted"
  case roleCreated = "role.created"
  case roleUpdated = "role.updated"
  case roleDeleted = "role.deleted"
  case roleAssignmentCreated = "role.assignment.created"
  case roleAssignmentDeleted = "role.assignment.deleted"
  case roleBoundToResource = "role.bound_to_resource"
  case roleUnboundFromResource = "role.unbound_from_resource"
  case scimEnabled = "scim.enabled"
  case scimDisabled = "scim.disabled"
  case serviceAccountCreated = "service_account.created"
  case serviceAccountUpdated = "service_account.updated"
  case serviceAccountDeleted = "service_account.deleted"
  case userAdded = "user.added"
  case userUpdated = "user.updated"
  case userDeleted = "user.deleted"
  case tenantMetadataUpdated = "tenant.metadata.updated"
  case tenantMicrosoftEntraMappingUpserted = "tenant.microsoft_entra_mapping.upserted"
  case tenantMicrosoftEntraMappingDeleted = "tenant.microsoft_entra_mapping.deleted"
  case tenantWorkloadIdentityProviderCreated = "tenant.workload_identity.provider.created"
  case tenantWorkloadIdentityProviderUpdated = "tenant.workload_identity.provider.updated"
  case tenantWorkloadIdentityProviderArchived = "tenant.workload_identity.provider.archived"
  case tenantWorkloadIdentityMappingCreated = "tenant.workload_identity.mapping.created"
  case tenantWorkloadIdentityMappingUpdated = "tenant.workload_identity.mapping.updated"
  case tenantWorkloadIdentityMappingArchived = "tenant.workload_identity.mapping.archived"
  case tenantWorkloadIdentityBindingCreated = "tenant.workload_identity.binding.created"
  case tenantWorkloadIdentityPrincipalProvisioned = "tenant.workload_identity.principal.provisioned"
  case tenantWorkloadIdentityAccessTokenIssued = "tenant.workload_identity.access_token.issued"
  case tenantAdminApiKeyCreated = "tenant.admin_api_key.created"
  case tenantAdminApiKeyUpdated = "tenant.admin_api_key.updated"
  case tenantAdminApiKeyDeleted = "tenant.admin_api_key.deleted"
  case tenantProjectApiKeyCreated = "tenant.project_api_key.created"
  case tenantTrustedAccessBusinessVerificationStarted =
    "tenant.trusted_access.business_verification.started"
  case tenantTrustedAccessApplicationSubmitted = "tenant.trusted_access.application.submitted"
  case tenantChatgptAccessTokenRevoked = "tenant.chatgpt_access_token.revoked"
  case tenantMigrationCompleted = "tenant.migration.completed"
  case tenantSsoMigrated = "tenant.sso.migrated"
  case tenantDomainsMigrated = "tenant.domains.migrated"
  case tenantSsoConnectionCreated = "tenant.sso_connection.created"
  case tenantSsoConnectionUpdated = "tenant.sso_connection.updated"
  case tenantSsoConnectionDeleted = "tenant.sso_connection.deleted"
  case tenantSsoConnectionSetupStarted = "tenant.sso_connection.setup.started"
  case tenantPolicyCreated = "tenant.policy.created"
  case tenantPolicyUpdated = "tenant.policy.updated"
  case tenantPolicyDeleted = "tenant.policy.deleted"
  case tenantPolicyAttached = "tenant.policy.attached"
  case tenantPolicyDetached = "tenant.policy.detached"
  case tenantPrincipalAuthenticationPolicyResolved =
    "tenant.principal_authentication_policy.resolved"
  case tenantScimSetupStarted = "tenant.scim.setup.started"
  case tenantScimDeletionRequested = "tenant.scim.deletion.requested"
  case tenantScimDirectoryCreated = "tenant.scim.directory.created"
  case tenantProductAccessPolicyUpdated = "tenant.product_access_policy.updated"
  case tenantResourceShareGrantCreated = "tenant.resource_share_grant.created"
  case tenantResourceShareGrantUpdated = "tenant.resource_share_grant.updated"
  case tenantResourceShareGrantAccepted = "tenant.resource_share_grant.accepted"
  case tenantResourceShareGrantDeclined = "tenant.resource_share_grant.declined"
  case tenantResourceShareGrantRevoked = "tenant.resource_share_grant.revoked"
  case tenantResourceShareGrantDeleted = "tenant.resource_share_grant.deleted"
  case tenantServiceAccountUpdated = "tenant.service_account.updated"
  case tenantServiceAccountDeleted = "tenant.service_account.deleted"
  case tenantServiceAccountTokenRevoked = "tenant.service_account.token.revoked"
  case tenantBillingOverageLimitUpdated = "tenant.billing.overage_limit.updated"
  case tenantBillingAlertsUpdated = "tenant.billing.alerts.updated"
  case tenantBillingInfoUpdated = "tenant.billing.info.updated"
  case tenantUsageLimitWorkspaceUpdated = "tenant.usage_limit.workspace.updated"
  case tenantUsageLimitGroupUpdated = "tenant.usage_limit.group.updated"
  case tenantUsageLimitUserUpdated = "tenant.usage_limit.user.updated"
  case tenantUsageLimitIncreaseRequestUpdated = "tenant.usage_limit.increase_request.updated"
  case tenantUsageLimitIncreaseRequestResolved = "tenant.usage_limit.increase_request.resolved"
  case tenantGroupCreated = "tenant.group.created"
  case tenantGroupUpdated = "tenant.group.updated"
  case tenantGroupDeleted = "tenant.group.deleted"
  case tenantGroupMemberAdded = "tenant.group.member.added"
  case tenantGroupMemberRemoved = "tenant.group.member.removed"
  case tenantMigrationRolloutStatusUpdated = "tenant.migration_rollout.status.updated"
  case tenantMigrationRolloutTierUpdated = "tenant.migration_rollout.tier.updated"
  case tenantRoleMetadataUpdated = "tenant.role.metadata.updated"
  case tenantCustomRoleCreated = "tenant.custom_role.created"
  case tenantCustomRoleUpdated = "tenant.custom_role.updated"
  case tenantCustomRoleDeleted = "tenant.custom_role.deleted"
  case tenantRoleAssignmentCreated = "tenant.role_assignment.created"
  case tenantRoleAssignmentDeleted = "tenant.role_assignment.deleted"
  case tenantResourceRoleAssignmentCreated = "tenant.resource_role_assignment.created"
  case tenantResourceRoleAssignmentDeleted = "tenant.resource_role_assignment.deleted"
  case tenantResourceAccessUpdated = "tenant.resource_access.updated"
  case tenantResourceAccessDeleted = "tenant.resource_access.deleted"
  case tenantAdsAccountOnboardingRedemption = "tenant.ads_account.onboarding.redemption"
  case tenantSessionPolicyCreated = "tenant.session_policy.created"
  case tenantSessionPolicyUpdated = "tenant.session_policy.updated"
  case tenantSessionPolicyDeleted = "tenant.session_policy.deleted"
  case tenantSessionRevocationStarted = "tenant.session_revocation.started"
  case tenantThirdPartyAppPolicyUpdated = "tenant.third_party_app_policy.updated"
  case tenantUserAdded = "tenant.user.added"
  case tenantUserUpdated = "tenant.user.updated"
  case tenantUserRemoved = "tenant.user.removed"
  case tenantUserLookedUp = "tenant.user.looked_up"
  case tenantUserInvited = "tenant.user.invited"
  case tenantMembershipRevoked = "tenant.membership.revoked"
  case tenantApiOrganizationInviteUpserted = "tenant.api_organization_invite.upserted"
  case tenantApiOrganizationInviteDeleted = "tenant.api_organization_invite.deleted"
  case tenantChatgptWorkspaceInviteUpserted = "tenant.chatgpt_workspace_invite.upserted"
  case tenantMembershipAccepted = "tenant.membership.accepted"
  case tenantMembershipDeclined = "tenant.membership.declined"
  case tenantWorkspaceInviteEmailSettingsUpdated = "tenant.workspace_invite_email_settings.updated"
}
