//
//  GroqCreateTranscriptionRequestLanguageAnyOf2.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public struct GroqCreateTranscriptionRequestLanguageAnyOf2: RawRepresentable, Codable, Hashable,
  Sendable
{
  public var rawValue: String

  public init(rawValue: String) {
    self.rawValue = rawValue
  }

  public static let en = Self(rawValue: "en")
  public static let zh = Self(rawValue: "zh")
  public static let de = Self(rawValue: "de")
  public static let es = Self(rawValue: "es")
  public static let ru = Self(rawValue: "ru")
  public static let ko = Self(rawValue: "ko")
  public static let fr = Self(rawValue: "fr")
  public static let ja = Self(rawValue: "ja")
  public static let pt = Self(rawValue: "pt")
  public static let tr = Self(rawValue: "tr")
  public static let pl = Self(rawValue: "pl")
  public static let ca = Self(rawValue: "ca")
  public static let nl = Self(rawValue: "nl")
  public static let ar = Self(rawValue: "ar")
  public static let sv = Self(rawValue: "sv")
  public static let it = Self(rawValue: "it")
  public static let id = Self(rawValue: "id")
  public static let hi = Self(rawValue: "hi")
  public static let fi = Self(rawValue: "fi")
  public static let vi = Self(rawValue: "vi")
  public static let he = Self(rawValue: "he")
  public static let uk = Self(rawValue: "uk")
  public static let el = Self(rawValue: "el")
  public static let ms = Self(rawValue: "ms")
  public static let cs = Self(rawValue: "cs")
  public static let ro = Self(rawValue: "ro")
  public static let da = Self(rawValue: "da")
  public static let hu = Self(rawValue: "hu")
  public static let ta = Self(rawValue: "ta")
  public static let no = Self(rawValue: "no")
  public static let th = Self(rawValue: "th")
  public static let ur = Self(rawValue: "ur")
  public static let hr = Self(rawValue: "hr")
  public static let bg = Self(rawValue: "bg")
  public static let lt = Self(rawValue: "lt")
  public static let la = Self(rawValue: "la")
  public static let mi = Self(rawValue: "mi")
  public static let ml = Self(rawValue: "ml")
  public static let cy = Self(rawValue: "cy")
  public static let sk = Self(rawValue: "sk")
  public static let te = Self(rawValue: "te")
  public static let fa = Self(rawValue: "fa")
  public static let lv = Self(rawValue: "lv")
  public static let bn = Self(rawValue: "bn")
  public static let sr = Self(rawValue: "sr")
  public static let az = Self(rawValue: "az")
  public static let sl = Self(rawValue: "sl")
  public static let kn = Self(rawValue: "kn")
  public static let et = Self(rawValue: "et")
  public static let mk = Self(rawValue: "mk")
  public static let br = Self(rawValue: "br")
  public static let eu = Self(rawValue: "eu")
  public static let isValue = Self(rawValue: "is")
  public static let hy = Self(rawValue: "hy")
  public static let ne = Self(rawValue: "ne")
  public static let mn = Self(rawValue: "mn")
  public static let bs = Self(rawValue: "bs")
  public static let kk = Self(rawValue: "kk")
  public static let sq = Self(rawValue: "sq")
  public static let sw = Self(rawValue: "sw")
  public static let gl = Self(rawValue: "gl")
  public static let mr = Self(rawValue: "mr")
  public static let pa = Self(rawValue: "pa")
  public static let si = Self(rawValue: "si")
  public static let km = Self(rawValue: "km")
  public static let sn = Self(rawValue: "sn")
  public static let yo = Self(rawValue: "yo")
  public static let so = Self(rawValue: "so")
  public static let af = Self(rawValue: "af")
  public static let oc = Self(rawValue: "oc")
  public static let ka = Self(rawValue: "ka")
  public static let be = Self(rawValue: "be")
  public static let tg = Self(rawValue: "tg")
  public static let sd = Self(rawValue: "sd")
  public static let gu = Self(rawValue: "gu")
  public static let am = Self(rawValue: "am")
  public static let yi = Self(rawValue: "yi")
  public static let lo = Self(rawValue: "lo")
  public static let uz = Self(rawValue: "uz")
  public static let fo = Self(rawValue: "fo")
  public static let ht = Self(rawValue: "ht")
  public static let ps = Self(rawValue: "ps")
  public static let tk = Self(rawValue: "tk")
  public static let nn = Self(rawValue: "nn")
  public static let mt = Self(rawValue: "mt")
  public static let sa = Self(rawValue: "sa")
  public static let lb = Self(rawValue: "lb")
  public static let my = Self(rawValue: "my")
  public static let bo = Self(rawValue: "bo")
  public static let tl = Self(rawValue: "tl")
  public static let mg = Self(rawValue: "mg")
  public static let asValue = Self(rawValue: "as")
  public static let tt = Self(rawValue: "tt")
  public static let haw = Self(rawValue: "haw")
  public static let ln = Self(rawValue: "ln")
  public static let ha = Self(rawValue: "ha")
  public static let ba = Self(rawValue: "ba")
  public static let jv = Self(rawValue: "jv")
  public static let su = Self(rawValue: "su")
  public static let yue = Self(rawValue: "yue")
}
