//
//  GroqCreateTranscriptionRequestLanguageAnyOf2.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum GroqCreateTranscriptionRequestLanguageAnyOf2: String, Codable, Hashable, Sendable {
  case en = "en"
  case zh = "zh"
  case de = "de"
  case es = "es"
  case ru = "ru"
  case ko = "ko"
  case fr = "fr"
  case ja = "ja"
  case pt = "pt"
  case tr = "tr"
  case pl = "pl"
  case ca = "ca"
  case nl = "nl"
  case ar = "ar"
  case sv = "sv"
  case it = "it"
  case id = "id"
  case hi = "hi"
  case fi = "fi"
  case vi = "vi"
  case he = "he"
  case uk = "uk"
  case el = "el"
  case ms = "ms"
  case cs = "cs"
  case ro = "ro"
  case da = "da"
  case hu = "hu"
  case ta = "ta"
  case no = "no"
  case th = "th"
  case ur = "ur"
  case hr = "hr"
  case bg = "bg"
  case lt = "lt"
  case la = "la"
  case mi = "mi"
  case ml = "ml"
  case cy = "cy"
  case sk = "sk"
  case te = "te"
  case fa = "fa"
  case lv = "lv"
  case bn = "bn"
  case sr = "sr"
  case az = "az"
  case sl = "sl"
  case kn = "kn"
  case et = "et"
  case mk = "mk"
  case br = "br"
  case eu = "eu"
  case isValue = "is"
  case hy = "hy"
  case ne = "ne"
  case mn = "mn"
  case bs = "bs"
  case kk = "kk"
  case sq = "sq"
  case sw = "sw"
  case gl = "gl"
  case mr = "mr"
  case pa = "pa"
  case si = "si"
  case km = "km"
  case sn = "sn"
  case yo = "yo"
  case so = "so"
  case af = "af"
  case oc = "oc"
  case ka = "ka"
  case be = "be"
  case tg = "tg"
  case sd = "sd"
  case gu = "gu"
  case am = "am"
  case yi = "yi"
  case lo = "lo"
  case uz = "uz"
  case fo = "fo"
  case ht = "ht"
  case ps = "ps"
  case tk = "tk"
  case nn = "nn"
  case mt = "mt"
  case sa = "sa"
  case lb = "lb"
  case my = "my"
  case bo = "bo"
  case tl = "tl"
  case mg = "mg"
  case asValue = "as"
  case tt = "tt"
  case haw = "haw"
  case ln = "ln"
  case ha = "ha"
  case ba = "ba"
  case jv = "jv"
  case su = "su"
  case yue = "yue"
}
