//
//  FireworksGatewayDatasetValidationFormat.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum FireworksGatewayDatasetValidationFormat: String, Codable, Hashable, Sendable {
  case dATASETVALIDATIONFORMATUNSPECIFIED = "DATASET_VALIDATION_FORMAT_UNSPECIFIED"
  case dATASETVALIDATIONFORMATCHAT = "DATASET_VALIDATION_FORMAT_CHAT"
  case dATASETVALIDATIONFORMATCHATRELAXED = "DATASET_VALIDATION_FORMAT_CHAT_RELAXED"
  case dATASETVALIDATIONFORMATRLOR = "DATASET_VALIDATION_FORMAT_RLOR"
  case dATASETVALIDATIONFORMATBATCHINFERENCESTRICT =
    "DATASET_VALIDATION_FORMAT_BATCH_INFERENCE_STRICT"
  case dATASETVALIDATIONFORMATBATCHINFERENCEALLOWTRAILINGASSISTANT =
    "DATASET_VALIDATION_FORMAT_BATCH_INFERENCE_ALLOW_TRAILING_ASSISTANT"
  case dATASETVALIDATIONFORMATBATCHINFERENCE = "DATASET_VALIDATION_FORMAT_BATCH_INFERENCE"
  case dATASETVALIDATIONFORMATDPO = "DATASET_VALIDATION_FORMAT_DPO"
}
