//
//  FireworksGatewayMetrics.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum FireworksGatewayMetrics: String, Codable, Hashable, Sendable {
  case mETRICSUNSPECIFIED = "METRICS_UNSPECIFIED"
  case rEPLICACOUNT = "REPLICA_COUNT"
  case aVERAGEREPLICACOUNT = "AVERAGE_REPLICA_COUNT"
  case lOAD = "LOAD"
  case cONCURRENTREQUESTS = "CONCURRENT_REQUESTS"
  case pROMPTCACHEHITRATE = "PROMPT_CACHE_HIT_RATE"
  case rEQUESTSTOTAL = "REQUESTS_TOTAL"
  case rEQUESTSERRORRATE = "REQUESTS_ERROR_RATE"
  case tOKENSPROMPTPERREQUEST = "TOKENS_PROMPT_PER_REQUEST"
  case tOKENSGENERATEDPERREQUEST = "TOKENS_GENERATED_PER_REQUEST"
  case sPECULATIVEHITTOTAL = "SPECULATIVE_HIT_TOTAL"
  case sPECULATIVEHITUSER = "SPECULATIVE_HIT_USER"
  case rEQUESTSPERSECOND = "REQUESTS_PER_SECOND"
  case tOKENSPERSECOND = "TOKENS_PER_SECOND"
  case tOKENSGENERATEDPERSECOND = "TOKENS_GENERATED_PER_SECOND"
  case tOKENSPROMPTPERSECOND = "TOKENS_PROMPT_PER_SECOND"
  case tOKENSPROMPTCACHEDPERSECOND = "TOKENS_PROMPT_CACHED_PER_SECOND"
  case lATENCY = "LATENCY"
  case gENERATIONQUEUELATENCY = "GENERATION_QUEUE_LATENCY"
  case pREFILLQUEUELATENCY = "PREFILL_QUEUE_LATENCY"
  case fIRSTTOKENLATENCY = "FIRST_TOKEN_LATENCY"
  case gENERATIONPERTOKENLATENCY = "GENERATION_PER_TOKEN_LATENCY"
  case sERVERLESSREQUESTSTOTAL = "SERVERLESS_REQUESTS_TOTAL"
  case sERVERLESSREQUESTSRATEMIRRORPERACCOUNT = "SERVERLESS_REQUESTS_RATE_MIRROR_PER_ACCOUNT"
  case sERVERLESSREQUESTSLIMITPERACCOUNT = "SERVERLESS_REQUESTS_LIMIT_PER_ACCOUNT"
  case sERVERLESSTOKENSPROMPTLIMITPERACCOUNT = "SERVERLESS_TOKENS_PROMPT_LIMIT_PER_ACCOUNT"
  case sERVERLESSTOKENSPROMPTRATEMIRRORPERACCOUNT =
    "SERVERLESS_TOKENS_PROMPT_RATE_MIRROR_PER_ACCOUNT"
  case sERVERLESSTOKENSGENERATEDLIMITPERACCOUNT = "SERVERLESS_TOKENS_GENERATED_LIMIT_PER_ACCOUNT"
  case sERVERLESSTOKENSGENERATEDRATEMIRRORPERACCOUNT =
    "SERVERLESS_TOKENS_GENERATED_RATE_MIRROR_PER_ACCOUNT"
  case sERVERLESSCACHEDPROMPTTOKENS = "SERVERLESS_CACHED_PROMPT_TOKENS"
  case sERVERLESSTOTALPROMPTTOKENS = "SERVERLESS_TOTAL_PROMPT_TOKENS"
}
