//
//  FireworksGatewayJobState.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum FireworksGatewayJobState: String, Codable, Hashable, Sendable {
  case jOBSTATEUNSPECIFIED = "JOB_STATE_UNSPECIFIED"
  case jOBSTATECREATING = "JOB_STATE_CREATING"
  case jOBSTATERUNNING = "JOB_STATE_RUNNING"
  case jOBSTATECOMPLETED = "JOB_STATE_COMPLETED"
  case jOBSTATEFAILED = "JOB_STATE_FAILED"
  case jOBSTATECANCELLED = "JOB_STATE_CANCELLED"
  case jOBSTATEDELETING = "JOB_STATE_DELETING"
  case jOBSTATEWRITINGRESULTS = "JOB_STATE_WRITING_RESULTS"
  case jOBSTATEVALIDATING = "JOB_STATE_VALIDATING"
  case jOBSTATEDELETINGCLEANINGUP = "JOB_STATE_DELETING_CLEANING_UP"
  case jOBSTATEPENDING = "JOB_STATE_PENDING"
  case jOBSTATEEXPIRED = "JOB_STATE_EXPIRED"
  case jOBSTATEREQUEUEING = "JOB_STATE_RE_QUEUEING"
  case jOBSTATECREATINGINPUTDATASET = "JOB_STATE_CREATING_INPUT_DATASET"
  case jOBSTATEIDLE = "JOB_STATE_IDLE"
  case jOBSTATECANCELLING = "JOB_STATE_CANCELLING"
  case jOBSTATEEARLYSTOPPED = "JOB_STATE_EARLY_STOPPED"
  case jOBSTATEPAUSED = "JOB_STATE_PAUSED"
  case jOBSTATEDELETED = "JOB_STATE_DELETED"
  case jOBSTATEARCHIVED = "JOB_STATE_ARCHIVED"
}
