//
//  FireworksGatewayUpdateRouterRequest.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public struct FireworksGatewayUpdateRouterRequest: Codable, Sendable {
  public var aliases: [String]?
  public var autoGenerated: Bool?
  public var createTime: String?
  public var createdBy: String?
  public var deployments: [String]?
  public var displayName: String?
  public var evenLoad: FireworksGatewayEvenLoadStrategy?
  public var model: String?
  public var publicValue: Bool?
  public var state: FireworksGatewayRouterState?
  public var status: FireworksGatewayStatus?
  public var weightedRandom: FireworksGatewayWeightedRandomStrategy?

  public init(
    aliases: [String]? = nil,
    autoGenerated: Bool? = nil,
    createTime: String? = nil,
    createdBy: String? = nil,
    deployments: [String]? = nil,
    displayName: String? = nil,
    evenLoad: FireworksGatewayEvenLoadStrategy? = nil,
    model: String? = nil,
    publicValue: Bool? = nil,
    state: FireworksGatewayRouterState? = nil,
    status: FireworksGatewayStatus? = nil,
    weightedRandom: FireworksGatewayWeightedRandomStrategy? = nil
  ) {
    self.aliases = aliases
    self.autoGenerated = autoGenerated
    self.createTime = createTime
    self.createdBy = createdBy
    self.deployments = deployments
    self.displayName = displayName
    self.evenLoad = evenLoad
    self.model = model
    self.publicValue = publicValue
    self.state = state
    self.status = status
    self.weightedRandom = weightedRandom
  }

  enum CodingKeys: String, CodingKey {
    case aliases
    case autoGenerated
    case createTime
    case createdBy
    case deployments
    case displayName
    case evenLoad
    case model
    case publicValue = "public"
    case state
    case status
    case weightedRandom
  }
}
