//
//  MistralObservabilityErrorCode.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum MistralObservabilityErrorCode: String, Codable, Hashable, Sendable {
  case uNKNOWNERROR = "UNKNOWN_ERROR"
  case vALIDATIONERROR = "VALIDATION_ERROR"
  case aUTHFORBIDDEN = "AUTH_FORBIDDEN"
  case aUTHFORBIDDENNOTWORKSPACEADMIN = "AUTH_FORBIDDEN_NOT_WORKSPACE_ADMIN"
  case aUTHFORBIDDENWORKSPACENOTFOUND = "AUTH_FORBIDDEN_WORKSPACE_NOT_FOUND"
  case aUTHFORBIDDENROLENOTFOUND = "AUTH_FORBIDDEN_ROLE_NOT_FOUND"
  case aUTHUNAUTHORIZED = "AUTH_UNAUTHORIZED"
  case fEATURENOTSUPPORTED = "FEATURE_NOT_SUPPORTED"
  case fIELDSBADREQUEST = "FIELDS_BAD_REQUEST"
  case fIELDSNOTFOUND = "FIELDS_NOT_FOUND"
  case sEARCHNOTFOUND = "SEARCH_NOT_FOUND"
  case sEARCHBADREQUEST = "SEARCH_BAD_REQUEST"
  case sEARCHSERVICEUNAVAILABLE = "SEARCH_SERVICE_UNAVAILABLE"
  case dATABASEERROR = "DATABASE_ERROR"
  case dATABASETIMEOUT = "DATABASE_TIMEOUT"
  case dATABASEUNAVAILABLE = "DATABASE_UNAVAILABLE"
  case dATABASEQUERYERROR = "DATABASE_QUERY_ERROR"
  case sEARCHFILTERTOSQLCONVERSIONERROR = "SEARCH_FILTER_TO_SQL_CONVERSION_ERROR"
  case jUDGECONVERSATIONFORMATERROR = "JUDGE_CONVERSATION_FORMAT_ERROR"
  case jUDGEMISTRALAPIERROR = "JUDGE_MISTRAL_API_ERROR"
  case jUDGEMISTRALAPITIMEOUT = "JUDGE_MISTRAL_API_TIMEOUT"
  case jUDGENAMEALREADYEXISTS = "JUDGE_NAME_ALREADY_EXISTS"
  case jUDGENOTFOUND = "JUDGE_NOT_FOUND"
  case jUDGEALREADYHASNEWVERSION = "JUDGE_ALREADY_HAS_NEW_VERSION"
  case jUDGEUSEDINCAMPAIGNCANNOTBEUPDATED = "JUDGE_USED_IN_CAMPAIGN_CANNOT_BE_UPDATED"
  case jUDGEDIDNOTCHANGE = "JUDGE_DID_NOT_CHANGE"
  case cAMPAIGNNOTFOUND = "CAMPAIGN_NOT_FOUND"
  case cAMPAIGNNOMATCHINGEVENTS = "CAMPAIGN_NO_MATCHING_EVENTS"
  case dATASETNOTFOUND = "DATASET_NOT_FOUND"
  case dATASETTASKNOTFOUND = "DATASET_TASK_NOT_FOUND"
  case dATASETRECORDNOTFOUND = "DATASET_RECORD_NOT_FOUND"
  case dATASETRECORDFORMATERROR = "DATASET_RECORD_FORMAT_ERROR"
  case aGENTNOTFOUND = "AGENT_NOT_FOUND"
  case aGENTMISTRALAPIERROR = "AGENT_MISTRAL_API_ERROR"
  case eVALUATIONNOTFOUND = "EVALUATION_NOT_FOUND"
  case eVALUATIONCURRENTLYRUNNING = "EVALUATION_CURRENTLY_RUNNING"
  case eVALUATIONRECORDNOTFOUND = "EVALUATION_RECORD_NOT_FOUND"
  case eVALUATIONRUNNOTFOUND = "EVALUATION_RUN_NOT_FOUND"
  case eVALUATIONRUNTRANSITIONISINVALID = "EVALUATION_RUN_TRANSITION_IS_INVALID"
  case eVALUATIONRUNTRANSITIONISRUNNINGALREADY = "EVALUATION_RUN_TRANSITION_IS_RUNNING_ALREADY"
  case eVALUATIONRUNTRANSITIONERROR = "EVALUATION_RUN_TRANSITION_ERROR"
  case tEMPLATEERROR = "TEMPLATE_ERROR"
  case tEMPLATESYNTAXERROR = "TEMPLATE_SYNTAX_ERROR"
  case pROJECTNAMEALREADYEXISTS = "PROJECT_NAME_ALREADY_EXISTS"
  case eVALUATIONNAMEALREADYEXISTS = "EVALUATION_NAME_ALREADY_EXISTS"
  case oPTIMIZATIONTRIALKEYALREADYEXISTS = "OPTIMIZATION_TRIAL_KEY_ALREADY_EXISTS"
  case tRACESFILTERQUERYPARSEERROR = "TRACES_FILTER_QUERY_PARSE_ERROR"
  case tRACENOTFOUND = "TRACE_NOT_FOUND"
  case sPANNOTFOUND = "SPAN_NOT_FOUND"
}
