//
//  MistralWorkflowEventType.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum MistralWorkflowEventType: String, Codable, Hashable, Sendable {
  case wORKFLOWEXECUTIONSTARTED = "WORKFLOW_EXECUTION_STARTED"
  case wORKFLOWEXECUTIONCOMPLETED = "WORKFLOW_EXECUTION_COMPLETED"
  case wORKFLOWEXECUTIONFAILED = "WORKFLOW_EXECUTION_FAILED"
  case wORKFLOWEXECUTIONCANCELED = "WORKFLOW_EXECUTION_CANCELED"
  case wORKFLOWEXECUTIONCONTINUEDASNEW = "WORKFLOW_EXECUTION_CONTINUED_AS_NEW"
  case wORKFLOWTASKTIMEDOUT = "WORKFLOW_TASK_TIMED_OUT"
  case wORKFLOWTASKFAILED = "WORKFLOW_TASK_FAILED"
  case cUSTOMTASKSTARTED = "CUSTOM_TASK_STARTED"
  case cUSTOMTASKINPROGRESS = "CUSTOM_TASK_IN_PROGRESS"
  case cUSTOMTASKCOMPLETED = "CUSTOM_TASK_COMPLETED"
  case cUSTOMTASKFAILED = "CUSTOM_TASK_FAILED"
  case cUSTOMTASKTIMEDOUT = "CUSTOM_TASK_TIMED_OUT"
  case cUSTOMTASKCANCELED = "CUSTOM_TASK_CANCELED"
  case aCTIVITYTASKSTARTED = "ACTIVITY_TASK_STARTED"
  case aCTIVITYTASKCOMPLETED = "ACTIVITY_TASK_COMPLETED"
  case aCTIVITYTASKRETRYING = "ACTIVITY_TASK_RETRYING"
  case aCTIVITYTASKFAILED = "ACTIVITY_TASK_FAILED"
}
