//
//  MistralTargetType.swift
//  HyperProxySwift
//
//  Created by HyperProxy on 13.09.2026.
//  Copyright © 2026 HyperProxy. All rights reserved.
//
// Maintainer-generated release artifact. Do not edit by hand.

import Foundation
import HyperProxyCore

public enum MistralTargetType: String, Codable, Hashable, Sendable {
  case uSER = "USER"
  case uSERGROUP = "USER_GROUP"
  case oRGANIZATION = "ORGANIZATION"
  case wORKSPACE = "WORKSPACE"
  case aPIKEY = "API_KEY"
  case aDMINAPIKEY = "ADMIN_API_KEY"
  case aPIKEYPOLICY = "API_KEY_POLICY"
  case sERVICEACCOUNT = "SERVICE_ACCOUNT"
  case aGENT = "AGENT"
  case sKILL = "SKILL"
  case pROMPT = "PROMPT"
  case kNOWLEDGEBASE = "KNOWLEDGE_BASE"
  case cUSTOMVOICE = "CUSTOM_VOICE"
  case dATASET = "DATASET"
  case fINETUNINGJOB = "FINE_TUNING_JOB"
  case bATCHJOB = "BATCH_JOB"
  case dATACAPTUREEXTRACTJOB = "DATA_CAPTURE_EXTRACT_JOB"
  case lECHATCONVERSATION = "LE_CHAT_CONVERSATION"
  case lECHATMEMORIES = "LE_CHAT_MEMORIES"
  case lECHATFLASHANSWERS = "LE_CHAT_FLASH_ANSWERS"
  case lECHATLOCALISATION = "LE_CHAT_LOCALISATION"
  case lECHATDATA = "LE_CHAT_DATA"
  case iNVOICE = "INVOICE"
  case wALLET = "WALLET"
  case mONTHLYLIMIT = "MONTHLY_LIMIT"
  case wORKSPACEMONTHLYLIMIT = "WORKSPACE_MONTHLY_LIMIT"
  case sHAREDBUDGET = "SHARED_BUDGET"
  case aUTORECHARGE = "AUTO_RECHARGE"
  case pAYMENTMETHOD = "PAYMENT_METHOD"
  case sUBSCRIPTION = "SUBSCRIPTION"
  case bILLINGINFO = "BILLING_INFO"
  case lIBRARY = "LIBRARY"
  case lIBRARYDOCUMENT = "LIBRARY_DOCUMENT"
  case iNTEGRATION = "INTEGRATION"
  case cONNECTORSGATEWAY = "CONNECTORS_GATEWAY"
  case cONNECTORSDEBUGGER = "CONNECTORS_DEBUGGER"
  case fEATUREPERMISSION = "FEATURE_PERMISSION"
  case sECRETSTOREENTRY = "SECRET_STORE_ENTRY"
  case cRAWLERCONFIG = "CRAWLER_CONFIG"
  case sHAREDRESOURCE = "SHARED_RESOURCE"
  case rATELIMITRULE = "RATE_LIMIT_RULE"
  case aPP = "APP"
  case dEPLOYMENT = "DEPLOYMENT"
  case dOMAIN = "DOMAIN"
  case pERSISTENTVOLUME = "PERSISTENT_VOLUME"
  case sECRET = "SECRET"
  case sERVICE = "SERVICE"
  case tRUSTEDISSUER = "TRUSTED_ISSUER"
}
